# Generated by Django 5.1.7 on 2025-04-02 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioAlbergue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Servicio de Albergue',
                'verbose_name_plural': 'Servicios de Albergue',
            },
        ),
        migrations.CreateModel(
            name='Albergue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=15)),
                ('entidad_federativa', models.CharField(max_length=100)),
                ('municipio_alcaldia', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(max_length=5)),
                ('calle', models.CharField(max_length=200)),
                ('numero_exterior', models.CharField(max_length=20)),
                ('referencias', models.TextField(blank=True, null=True)),
                ('nombre_responsable', models.CharField(max_length=100)),
                ('apellido_responsable', models.CharField(max_length=100)),
                ('correo_responsable', models.EmailField(max_length=254)),
                ('capacidad_actual', models.PositiveIntegerField(default=0)),
                ('capacidad_maxima', models.PositiveIntegerField(default=0)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('sitio_web', models.URLField(blank=True, null=True)),
                ('imagen1', models.ImageField(blank=True, null=True, upload_to='albergues/')),
                ('imagen2', models.ImageField(blank=True, null=True, upload_to='albergues/')),
                ('imagen3', models.ImageField(blank=True, null=True, upload_to='albergues/')),
                ('imagen4', models.ImageField(blank=True, null=True, upload_to='albergues/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='albergue', to=settings.AUTH_USER_MODEL)),
                ('servicios', models.ManyToManyField(to='usuarios.servicioalbergue')),
            ],
            options={
                'verbose_name': 'Albergue',
                'verbose_name_plural': 'Albergues',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_persona', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario Persona',
                'verbose_name_plural': 'Usuarios Personas',
            },
        ),
    ]
