# Generated by Django 5.1.7 on 2025-04-06 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avistamiento_Perros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avistamientoperro',
            name='estado_perro',
            field=models.CharField(choices=[('S', 'Saludable'), ('H', 'Herido'), ('D', 'Desnutrido'), ('E', 'Enfermo'), ('Ag', 'Agresivo'), ('As', 'Asustado')], default='S', max_length=10),
        ),
        migrations.AlterField(
            model_name='avistamientoperro',
            name='sexo',
            field=models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra'), ('D', 'Desconocido')], default='D', max_length=30),
        ),
        migrations.AlterField(
            model_name='avistamientoperro',
            name='tamaño',
            field=models.CharField(choices=[('P', 'Pequeño'), ('M', 'Mediano'), ('G', 'Grande'), ('Gi', 'Gigante')], max_length=10),
        ),
    ]
